<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PageSectionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('page_sections')->delete();
        
        \DB::table('page_sections')->insert(array (
            0 => 
            array (
                'id' => 1,
                'section' => '<div class="main-banner light-blue-bg">
<div class="rocket"><img class="img-fluid" src="assets/images/rocket.gif" alt=""></div>
<div class="banner-text text-white">
<h2 class="title text-white">SEOhub - Multipurpose Bootstrap 4 Template</h2>
<p>Bootstrap 4 based Powerful Responsive HTML5 Template with 5 stunning home pages The fastest and easiest way to start new projects and startups</p>
<a target="_blank" class="button white purchase-btn" href="https://themeforest.net/item/seohub-seo-marketing-social-media-multipurpose-html5-template/20234006/?ref=Potenzaglobalsolutions"><i class="fa fa-cart-arrow-down" aria-hidden="true"></i> Purchase now</a>
<a class="ml-3" href="https://getbootstrap.com/"><img class="img-fluid" src="assets/images/bootstrap_img.png" alt=""></a>
</div>
<div id="rev_slider_12_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="seo-intro" style="margin:0px auto;background-color:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
<!-- START REVOLUTION SLIDER 5.2.6 fullwidth mode -->
<div id="rev_slider_12_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.2.6">
<ul>	<!-- SLIDE  -->
<li data-index="rs-20" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
<!-- MAIN IMAGE -->
<img src="assets/revolution/images/bg.png" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
<!-- LAYERS -->

<!-- LAYER NR. 1 -->
<div class="tp-caption  tp-resizeme" id="slide-20-layer-12" data-x="909" data-y="302" data-width="[\'auto\']" data-height="[\'auto\']" data-transform_idle="o:1;" data-transform_in="x:50px;opacity:0;s:1080;e:Power2.easeInOut;" data-transform_out="opacity:0;s:220;" data-start="10" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; white-space: nowrap; font-family:Arial, sans-serif; font-size: 180px; line-height: 180px; font-weight: 800; color: rgba(255, 255, 255, 0.2);">
<div class="rs-looped rs-slideloop" data-easing="easeInQuad" data-speed="40" data-xs="750" data-xe="-1700" data-ys="0" data-ye="0">SEOHUB </div></div>

<!-- LAYER NR. 2 -->
<div class="tp-caption   tp-resizeme" id="slide-20-layer-1" data-x="747" data-y="307" data-width="[\'none\',\'none\',\'none\',\'none\']" data-height="[\'none\',\'none\',\'none\',\'none\']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:710;e:Power2.easeInOut;" data-transform_out="rZ:0deg;sX:0.7;sY:0.7;opacity:0;s:300;" data-mask_out="x:0;y:0;s:inherit;e:inherit;" data-start="200" data-responsive_offset="on" style="z-index: 6;"><img src="assets/revolution/images/effect_4.png" alt="" data-ww="708px" data-hh="432px" data-no-retina> </div>

<!-- LAYER NR. 3 -->
<div class="tp-caption   tp-resizeme rs-parallaxlevel-3" id="slide-20-layer-2" data-x="901" data-y="112" data-width="[\'none\',\'none\',\'none\',\'none\']" data-height="[\'none\',\'none\',\'none\',\'none\']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:1150;e:Power2.easeInOut;" data-transform_out="opacity:0;s:300;" data-start="1470" data-responsive_offset="on" style="z-index: 7;"><img src="assets/revolution/images/effect_1.png" alt="" data-ww="266px" data-hh="189px" data-no-retina> </div>

<!-- LAYER NR. 4 -->
<div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-20-layer-3" data-x="1282" data-y="462" data-width="[\'none\',\'none\',\'none\',\'none\']" data-height="[\'none\',\'none\',\'none\',\'none\']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:1150;e:Power2.easeInOut;" data-transform_out="opacity:0;s:300;" data-start="1930" data-responsive_offset="on" style="z-index: 8;"><img src="assets/revolution/images/effect_2.png" alt="" data-ww="190px" data-hh="200px" data-no-retina> </div>

<!-- LAYER NR. 5 -->
<div class="tp-caption   tp-resizeme rs-parallaxlevel-3" id="slide-20-layer-4" data-x="778" data-y="461" data-width="[\'none\',\'none\',\'none\',\'none\']" data-height="[\'none\',\'none\',\'none\',\'none\']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:1150;e:Power2.easeInOut;" data-transform_out="opacity:0;s:300;" data-start="2380" data-responsive_offset="on" style="z-index: 9;"><img src="assets/revolution/images/effect_3.png" alt="" data-ww="158px" data-hh="158px" data-no-retina> </div>

<!-- LAYER NR. 6 -->
<div class="tp-caption   tp-resizeme rs-parallaxlevel-2" id="slide-20-layer-5" data-x="1085" data-y="669" data-width="[\'none\',\'none\',\'none\',\'none\']" data-height="[\'none\',\'none\',\'none\',\'none\']" data-transform_idle="o:1;" data-transform_in="y:-50px;opacity:0;s:1150;e:Power2.easeInOut;" data-transform_out="opacity:0;s:300;" data-start="2840" data-responsive_offset="on" style="z-index: 10;"><img src="assets/revolution/images/effect_5.png" alt="" data-ww="234px" data-hh="234px" data-no-retina> </div>

<!-- LAYER NR. 7 -->
<div class="tp-caption   tp-resizeme" id="slide-20-layer-8" data-x="680" data-y="286" data-width="[\'none\',\'none\',\'none\',\'none\']" data-height="[\'none\',\'none\',\'none\',\'none\']" data-transform_idle="o:1;" data-transform_in="x:50px;opacity:0;s:1100;e:Power2.easeInOut;" data-transform_out="opacity:0;s:300;" data-start="1000" data-responsive_offset="on" style="z-index: 11;"><img src="assets/revolution/images/effect_6.png" alt="" data-ww="208px" data-hh="164px" data-no-retina> </div>

<!-- LAYER NR. 8 -->
<div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-20-layer-6" data-x="751" data-y="173" data-width="[\'none\',\'none\',\'none\',\'none\']" data-height="[\'none\',\'none\',\'none\',\'none\']" data-transform_idle="o:1;" data-transform_in="x:50px;opacity:0;s:1480;e:Power2.easeInOut;" data-transform_out="opacity:0;s:300;" data-start="1000" data-responsive_offset="on" style="z-index: 12;"><img src="assets/revolution/images/tablet.png" alt="" data-ww="568px" data-hh="703px" data-no-retina> </div>

<!-- LAYER NR. 9 -->
<div class="tp-caption   tp-resizeme rs-parallaxlevel-2" id="slide-20-layer-7" data-x="1132" data-y="277" data-width="[\'none\',\'none\',\'none\',\'none\']" data-height="[\'none\',\'none\',\'none\',\'none\']" data-transform_idle="o:1;" data-transform_in="x:-50px;opacity:0;s:1490;e:Power2.easeInOut;" data-transform_out="opacity:0;s:300;" data-start="1130" data-responsive_offset="on" style="z-index: 13;"><img src="assets/revolution/images/mobile.png" alt="" data-ww="322px" data-hh="437px" data-no-retina> </div>

<!-- LAYER NR. 10 -->
<div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-20-layer-9" data-x="1409" data-y="311" data-width="[\'none\',\'none\',\'none\',\'none\']" data-height="[\'none\',\'none\',\'none\',\'none\']" data-transform_idle="o:1;" data-transform_in="x:-50px;opacity:0;s:1250;e:Power2.easeInOut;" data-transform_out="opacity:0;s:300;" data-start="2000" data-responsive_offset="on" style="z-index: 14;"><img src="assets/revolution/images/effect_6.png" alt="" data-ww="147px" data-hh="116px" data-no-retina> </div>

<!-- LAYER NR. 11 -->
<div class="tp-caption   tp-resizeme" id="slide-20-layer-10" data-x="700" data-y="655" data-width="[\'none\',\'none\',\'none\',\'none\']" data-height="[\'none\',\'none\',\'none\',\'none\']" data-transform_idle="o:1;" data-transform_in="x:50px;opacity:0;s:1370;e:Power2.easeInOut;" data-transform_out="opacity:0;s:300;" data-start="1660" data-responsive_offset="on" style="z-index: 15;"><img src="assets/revolution/images/target_bord.png" alt="" data-ww="202px" data-hh="202px" data-no-retina> </div>

<!-- LAYER NR. 12 -->
<div class="tp-caption   tp-resizeme rs-parallaxlevel-3" id="slide-20-layer-11" data-x="1373" data-y="225" data-width="[\'none\',\'none\',\'none\',\'none\']" data-height="[\'none\',\'none\',\'none\',\'none\']" data-transform_idle="o:1;" data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:1340;e:Power2.easeInOut;" data-transform_out="opacity:0;s:300;" data-start="2150" data-responsive_offset="on" style="z-index: 16;"><img src="assets/revolution/images/rocket.png" alt="" data-ww="112px" data-hh="112px" data-no-retina> </div>
</li>
</ul>
<div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>	</div>
</div><!-- END REVOLUTION SLIDER -->
</div>',
                'section_nickname' => 'Paralax Header',
                'order' => 2,
                'created_at' => '2022-01-12 23:11:11',
                'updated_at' => '2022-01-12 23:55:55',
                'deleted_at' => NULL,
                'published' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'section' => '<div id="rev_slider_17_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="seo-5" data-source="gallery" style="margin:0px auto;background-color:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
<!-- START REVOLUTION SLIDER 5.3.0.2.1 auto mode -->
<div id="rev_slider_17_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.3.0.2.1">
<ul>
<!-- SLIDE  -->
<li data-index="rs-55" data-transition="random-static,random-premium,random" data-slotamount="default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-randomtransition="on" data-easein="default,default,default,default" data-easeout="default,default,default,default" data-masterspeed="default,default,default,default" data-thumb="" data-rotate="0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
<!-- MAIN IMAGE -->
<img src="revolution/assets/dummy.png" style="background-color:#2046f2" alt="" data-lazyload="revolution/assets/transparent.png" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
<!-- LAYERS -->
<!-- LAYER NR. 1 -->
<div class="tp-caption   tp-resizeme" id="slide-55-layer-4" data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'1\',\'1\',\'1\',\'1\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'-190\',\'-190\',\'-190\',\'-190\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames=\'[{"delay":500,"split":"chars","splitdelay":0.05,"speed":2000,"frame":"0","from":"x:[105%];z:0;rX:45deg;rY:0deg;rZ:90deg;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'center\',\'center\',\'center\',\'center\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; white-space: nowrap; font-size: 74px; line-height: 82px; font-weight: 900; color: rgba(255, 255, 255, 1.00);font-family: \'Poppins\', sans-serif;">Use our marketing services
<br> grow your business </div>
<!-- LAYER NR. 3 -->
<div class="tp-caption   tp-resizeme packages-text" id="slide-55-layer-6" data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'0\',\'0\',\'0\',\'0\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'-50\',\'-50\',\'-50\',\'-50\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames=\'[{"delay":1930,"speed":1000,"frame":"0","from":"z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; white-space: nowrap; font-size: 16px; line-height: 18px; font-weight: 900; color: rgba(255, 255, 255, 1.00);font-family: \'Poppins\', sans-serif;">Packages from just $299 per month. </div>
<!-- LAYER NR. 4 -->
<div class="tp-caption rev-btn button black tp-resizeme rev-left-button" id="slide-55-layer-7" data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'-110\',\'-110\',\'-3000\',\'-3000\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'40\',\'20\',\'1000\',\'1000\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-responsive="on" data-responsive_offset="on" data-frames=\'[{"delay":2650,"speed":1000,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style="z-index: 8; cursor:pointer;">Get started now </div>
<!-- LAYER NR. 5 -->
<div class="tp-caption rev-btn  tp-resizeme button white rev-right-button" id="slide-55-layer-8" data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'110\',\'110\',\'110\',\'110\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'40\',\'20\',\'20\',\'20\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-responsive_offset="on" data-frames=\'[{"delay":2650,"speed":1000,"frame":"0","from":"x:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style="z-index: 9;cursor:pointer;">Discover more </div>
<!-- LAYER NR. 6 -->
<div class="tp-caption   tp-resizeme" id="slide-55-layer-10" data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'0\',\'0\',\'0\',\'0\']" data-y="[\'bottom\',\'bottom\',\'bottom\',\'bottom\']" data-voffset="[\'-65\',\'-65\',\'-65\',\'-65\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":3370,"speed":1000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 10;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'1018px\',\'1018px\',\'1018px\',\'1018px\']" data-hh="[\'298px\',\'298px\',\'298px\',\'298px\']" data-lazyload="revolution/assets/91dfe-12.png" data-no-retina> </div>
<!-- LAYER NR. 7 -->
<div class="tp-caption   tp-resizeme" id="slide-55-layer-11" data-x="[\'right\',\'right\',\'right\',\'right\']" data-hoffset="[\'-660\',\'-660\',\'-660\',\'-660\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'-100\',\'-100\',\'-100\',\'-100\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":4090,"speed":1000,"frame":"0","from":"x:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 11;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'682px\',\'682px\',\'682px\',\'682px\']" data-hh="[\'428px\',\'428px\',\'428px\',\'428px\']" data-lazyload="revolution/assets/8cffe-z2.png" data-no-retina> </div>
<!-- LAYER NR. 8 -->
<div class="tp-caption   tp-resizeme" id="slide-55-layer-12" data-x="[\'left\',\'left\',\'left\',\'left\']" data-hoffset="[\'-659\',\'-659\',\'-659\',\'-659\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'-101\',\'-101\',\'-101\',\'-101\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":4090,"speed":1000,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 12;"><img src="revolution/assets/dummy.png" alt="" data-ww="" data-hh="" data-lazyload="revolution/assets/8cffe-z1.png" data-no-retina> </div>
<!-- LAYER NR. 9 -->
<div class="tp-caption   tp-resizeme" id="slide-55-layer-13" data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'0\',\'0\',\'0\',\'0\']" data-y="[\'top\',\'top\',\'top\',\'top\']" data-voffset="[\'-220\',\'-220\',\'-220\',\'-220\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":4810,"speed":1000,"frame":"0","from":"y:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 13;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'313px\',\'313px\',\'313px\',\'313px\']" data-hh="[\'327px\',\'327px\',\'327px\',\'327px\']" data-lazyload="revolution/assets/8f327-z3.png" data-no-retina> </div>
<!-- LAYER NR. 10 -->
<div class="tp-caption   tp-resizeme" id="slide-55-layer-15" data-x="[\'left\',\'left\',\'left\',\'left\']" data-hoffset="[\'-510\',\'-510\',\'-510\',\'-510\']" data-y="[\'bottom\',\'bottom\',\'bottom\',\'bottom\']" data-voffset="[\'-390\',\'-390\',\'-390\',\'-390\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":4820,"speed":1000,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 14;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'531auto\',\'531auto\',\'531auto\',\'531auto\']" data-hh="[\'658px\',\'658px\',\'658px\',\'658px\']" data-lazyload="revolution/assets/e5a7f-z4.png" data-no-retina> </div>
<!-- LAYER NR. 11 -->
<div class="tp-caption   tp-resizeme" id="slide-55-layer-17" data-x="[\'right\',\'right\',\'right\',\'right\']" data-hoffset="[\'-320\',\'-320\',\'-320\',\'-320\']" data-y="[\'bottom\',\'bottom\',\'bottom\',\'bottom\']" data-voffset="[\'-180\',\'-180\',\'-180\',\'-180\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":4810,"speed":1000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 15;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'336px\',\'336px\',\'336px\',\'336px\']" data-hh="[\'451px\',\'451px\',\'451px\',\'451px\']" data-lazyload="revolution/assets/d9342-z5.png" data-no-retina> </div>
</li>
<!-- SLIDE  -->
<li data-index="rs-56" data-transition="random-static,random-premium,random" data-slotamount="default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-randomtransition="on" data-easein="default,default,default,default" data-easeout="default,default,default,default" data-masterspeed="300,default,default,default" data-thumb="" data-rotate="0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
<!-- MAIN IMAGE -->
<img src="revolution/assets/dummy.png" style="background-color:#2046f1" alt="" data-lazyload="revolution/assets/transparent.png" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="2" class="rev-slidebg" data-no-retina>
<!-- LAYERS -->
<!-- LAYER NR. 12 -->
<div class="tp-caption   tp-resizeme" id="slide-56-layer-26" data-x="[\'left\',\'left\',\'left\',\'left\']" data-hoffset="[\'-495\',\'-495\',\'-495\',\'-495\']" data-y="[\'top\',\'top\',\'top\',\'top\']" data-voffset="[\'0\',\'0\',\'0\',\'0\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":310,"speed":1000,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'2300px\',\'2300px\',\'2300px\',\'2300px\']" data-hh="[\'1626px\',\'1626px\',\'1626px\',\'1626px\']" data-lazyload="revolution/assets/1dec9-d1.png" data-no-retina> </div>
<!-- LAYER NR. 13 -->
<div class="tp-caption   tp-resizeme" id="slide-56-layer-4" data-x="[\'right\',\'right\',\'right\',\'right\']" data-hoffset="[\'50\',\'50\',\'50\',\'50\']" data-y="[\'top\',\'top\',\'top\',\'top\']" data-voffset="[\'189\',\'189\',\'189\',\'189\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames=\'[{"delay":530,"speed":1000,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeIn"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeOut"}]\' data-textalign="[\'right\',\'right\',\'right\',\'right\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; white-space: nowrap; font-size: 74px; line-height: 74px; font-weight: 900; color: rgba(255, 255, 255, 1.00);font-family: \'Poppins\', sans-serif;">
We are an expert
<br>SEO marketer </div>
<!-- LAYER NR. 15 -->
<div class="tp-caption   tp-resizeme packages-text" id="slide-56-layer-6" data-x="[\'right\',\'right\',\'right\',\'right\']" data-hoffset="[\'50\',\'50\',\'50\',\'50\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'-10\',\'-10\',\'-10\',\'-10\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames=\'[{"delay":1980,"speed":1000,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'right\',\'right\',\'right\',\'right\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8; white-space: nowrap; font-size: 16px; line-height: 18px; font-weight: 900; color: rgba(255, 255, 255, 1.00);font-family: \'Poppins\', sans-serif;">Packages from just $299 per month. </div>
<!-- LAYER NR. 16 -->
<div class="tp-caption rev-btn button black tp-resizeme rev-right-slide-btn" id="slide-56-layer-7" data-x="[\'right\',\'right\',\'right\',\'right\']" data-hoffset="[\'220\',\'220\',\'220\',\'220\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'50\',\'50\',\'50\',\'50\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-responsive_offset="on" data-frames=\'[{"delay":3200,"speed":1000,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style="z-index: 9; cursor:pointer;">SEO Prices </div>
<!-- LAYER NR. 17 -->
<div class="tp-caption rev-btn  tp-resizeme button white" id="slide-56-layer-8" data-x="[\'right\',\'right\',\'right\',\'right\']" data-hoffset="[\'50\',\'50\',\'50\',\'50\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'50\',\'50\',\'50\',\'50\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-responsive_offset="on" data-frames=\'[{"delay":2540,"speed":1000,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style="z-index: 10; cursor:pointer;">Free E-Book </div>
<!-- LAYER NR. 18 -->
<div class="tp-caption   tp-resizeme" id="slide-56-layer-12" data-x="[\'left\',\'left\',\'left\',\'left\']" data-hoffset="[\'-200\',\'-200\',\'-200\',\'-200\']" data-y="[\'top\',\'top\',\'top\',\'top\']" data-voffset="[\'150\',\'150\',\'150\',\'150\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":3920,"speed":1000,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 11;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'261px\',\'261px\',\'261px\',\'261px\']" data-hh="[\'127px\',\'127px\',\'127px\',\'127px\']" data-lazyload="revolution/assets/861ee-c1.png" data-no-retina> </div>
<!-- LAYER NR. 19 -->
<div class="tp-caption   tp-resizeme" id="slide-56-layer-14" data-x="[\'right\',\'right\',\'right\',\'right\']" data-hoffset="[\'-90\',\'-90\',\'-90\',\'-90\']" data-y="[\'top\',\'top\',\'top\',\'top\']" data-voffset="[\'100\',\'100\',\'100\',\'100\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":3920,"speed":1000,"frame":"0","from":"x:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 12;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'182px\',\'182px\',\'182px\',\'182px\']" data-hh="[\'83px\',\'83px\',\'83px\',\'83px\']" data-lazyload="revolution/assets/8b7de-c2.png" data-no-retina> </div>
<!-- LAYER NR. 20 -->
<div class="tp-caption   tp-resizeme" id="slide-56-layer-16" data-x="[\'right\',\'right\',\'right\',\'right\']" data-hoffset="[\'-200\',\'-200\',\'-200\',\'-200\']" data-y="[\'bottom\',\'bottom\',\'bottom\',\'bottom\']" data-voffset="[\'130\',\'130\',\'130\',\'130\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":3920,"speed":1000,"frame":"0","from":"x:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 13;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'247px\',\'247px\',\'247px\',\'247px\']" data-hh="[\'126px\',\'126px\',\'126px\',\'126px\']" data-lazyload="revolution/assets/427e6-c3.png" data-no-retina> </div>
<!-- LAYER NR. 21 -->
<div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-56-layer-18" data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'-290\',\'-290\',\'-290\',\'-290\']" data-y="[\'bottom\',\'bottom\',\'bottom\',\'bottom\']" data-voffset="[\'0\',\'0\',\'0\',\'0\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":6500,"speed":1000,"frame":"0","from":"x:0px;rX:0deg;","mask":"x:stage_left;y:stage_bottom;s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":1000,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 14;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'297px\',\'297px\',\'297px\',\'297px\']" data-hh="[\'695px\',\'695px\',\'695px\',\'695px\']" data-lazyload="revolution/assets/cd3dc-r2.png" data-no-retina> </div>
<!-- LAYER NR. 22 -->
<div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-56-layer-24" data-x="[\'left\',\'left\',\'left\',\'left\']" data-hoffset="[\'20\',\'20\',\'20\',\'20\']" data-y="[\'bottom\',\'bottom\',\'bottom\',\'bottom\']" data-voffset="[\'-30\',\'-30\',\'-30\',\'-30\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":4620,"speed":1000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 15;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'1044px\',\'1044px\',\'1044px\',\'1044px\']" data-hh="[\'216px\',\'216px\',\'216px\',\'216px\']" data-lazyload="revolution/assets/a9c45-f2.png" data-no-retina> </div>
<!-- LAYER NR. 23 -->
<div class="tp-caption   tp-resizeme rs-parallaxlevel-2" id="slide-56-layer-23" data-x="[\'left\',\'left\',\'left\',\'left\']" data-hoffset="[\'24\',\'24\',\'24\',\'24\']" data-y="[\'bottom\',\'bottom\',\'bottom\',\'bottom\']" data-voffset="[\'-45\',\'-45\',\'-45\',\'-45\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":5120,"speed":1000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 16;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'1034px\',\'1034px\',\'1034px\',\'1034px\']" data-hh="[\'214px\',\'214px\',\'214px\',\'214px\']" data-lazyload="revolution/assets/a9c45-f1.png" data-no-retina> </div>
<!-- LAYER NR. 24 -->
<div class="tp-caption   tp-resizeme rs-parallaxlevel-3" id="slide-56-layer-22" data-x="[\'left\',\'left\',\'left\',\'left\']" data-hoffset="[\'32\',\'32\',\'32\',\'32\']" data-y="[\'bottom\',\'bottom\',\'bottom\',\'bottom\']" data-voffset="[\'-53\',\'-53\',\'-53\',\'-53\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":5610,"speed":1000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 17;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'1016px\',\'1016px\',\'1016px\',\'1016px\']" data-hh="[\'210px\',\'210px\',\'210px\',\'210px\']" data-lazyload="revolution/assets/a4659-f3.png" data-no-retina> </div>
</li>
<!-- SLIDE  -->
<li data-index="rs-57" data-transition="random-static,random-premium,random" data-slotamount="default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-randomtransition="on" data-easein="default,default,default,default" data-easeout="default,default,default,default" data-masterspeed="default,default,default,default" data-thumb="" data-rotate="0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
<!-- MAIN IMAGE -->
<img src="revolution/assets/dummy.png" style="background-color:#0f34d8" alt="" data-lazyload="revolution/assets/transparent.png" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="2" class="rev-slidebg" data-no-retina>
<!-- LAYERS -->
<!-- LAYER NR. 25 -->
<div class="tp-caption   tp-resizeme" id="slide-57-layer-4" data-x="[\'right\',\'right\',\'right\',\'right\']" data-hoffset="[\'50\',\'50\',\'50\',\'50\']" data-y="[\'top\',\'top\',\'top\',\'top\']" data-voffset="[\'190\',\'190\',\'190\',\'190\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames=\'[{"delay":500,"speed":1000,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeIn"},{"delay":"wait","speed":310,"frame":"999","to":"opacity:0;","ease":"Power3.easeOut"}]\' data-textalign="[\'right\',\'right\',\'right\',\'right\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; white-space: nowrap; font-size: 74px; line-height: 74px; font-weight: 900; color: rgba(255, 255, 255, 1.00);font-family: \'Poppins\', sans-serif;">Guaranteed increase of
<br>your website Traffic </div>
<!-- LAYER NR. 27 -->
<div class="tp-caption   tp-resizeme packages-text" id="slide-57-layer-6" data-x="[\'right\',\'right\',\'right\',\'right\']" data-hoffset="[\'50\',\'50\',\'50\',\'50\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'0\',\'0\',\'0\',\'0\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames=\'[{"delay":1940,"speed":1000,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":310,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'right\',\'right\',\'right\',\'right\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; white-space: nowrap; font-size: 16px; line-height: 18px; font-weight: 900; color: rgba(255, 255, 255, 1.00);font-family: \'Poppins\', sans-serif;">Packages from just $299 per month. </div>
<!-- LAYER NR. 28 -->
<div class="tp-caption rev-btn button black tp-resizeme rev-right-slide-btn" id="slide-57-layer-7" data-x="[\'right\',\'right\',\'right\',\'right\']" data-hoffset="[\'220\',\'220\',\'220\',\'220\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'60\',\'60\',\'60\',\'60\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-responsive_offset="on" data-frames=\'[{"delay":3230,"speed":1000,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":310,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style="z-index: 8; cursor:pointer;">SEO Prices </div>
<!-- LAYER NR. 29 -->
<div class="tp-caption rev-btn  tp-resizeme button white" id="slide-57-layer-8" data-x="[\'right\',\'right\',\'right\',\'right\']" data-hoffset="[\'50\',\'50\',\'50\',\'50\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'60\',\'60\',\'60\',\'60\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-responsive_offset="on" data-frames=\'[{"delay":2580,"speed":1000,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":310,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style="z-index: 9; cursor:pointer;">Free E-Book </div>
<!-- LAYER NR. 30 -->
<div class="tp-caption   tp-resizeme" id="slide-57-layer-29" data-x="[\'left\',\'left\',\'left\',\'left\']" data-hoffset="[\'-201\',\'-201\',\'-201\',\'-201\']" data-y="[\'top\',\'top\',\'top\',\'top\']" data-voffset="[\'112\',\'112\',\'112\',\'112\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":4000,"speed":1000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":310,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 10;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'594px\',\'594px\',\'594px\',\'594px\']" data-hh="[\'541px\',\'541px\',\'541px\',\'541px\']" data-lazyload="revolution/assets/0497b-x3.png" data-no-retina> </div>
<!-- LAYER NR. 31 -->
<div class="tp-caption   tp-resizeme" id="slide-57-layer-27" data-x="[\'center\',\'center\',\'center\',\'center\']" data-hoffset="[\'-399\',\'-399\',\'-399\',\'-399\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'738\',\'738\',\'738\',\'738\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":3280,"speed":1000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":310,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 11;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'3328px\',\'3328px\',\'3328px\',\'3328px\']" data-hh="[\'996px\',\'996px\',\'996px\',\'996px\']" data-lazyload="revolution/assets/4c203-x1.png" data-no-retina> </div>
<!-- LAYER NR. 32 -->
<div class="tp-caption   tp-resizeme" id="slide-57-layer-30" data-x="[\'left\',\'left\',\'left\',\'left\']" data-hoffset="[\'-158\',\'-158\',\'-158\',\'-158\']" data-y="[\'middle\',\'middle\',\'middle\',\'middle\']" data-voffset="[\'265\',\'265\',\'265\',\'265\']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames=\'[{"delay":4690,"speed":1000,"frame":"0","from":"opacity:0;","to":"o:1;rZ:358;","ease":"Power3.easeInOut"},{"delay":"wait","speed":310,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]\' data-textalign="[\'inherit\',\'inherit\',\'inherit\',\'inherit\']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 12;"><img src="revolution/assets/dummy.png" alt="" data-ww="[\'571px\',\'571px\',\'571px\',\'571px\']" data-hh="[\'41px\',\'41px\',\'41px\',\'41px\']" data-lazyload="revolution/assets/6e017-x2.png" data-no-retina> </div>
</li>
</ul>
<div class="tp-bannertimer" style="height: 5px; background-color: rgba(0, 0, 0, 0.15);"></div>
</div>
</div>',
                'section_nickname' => 'Homepage Rev Slider',
                'order' => 1,
                'created_at' => '2022-01-12 23:40:16',
                'updated_at' => '2022-01-12 23:40:20',
                'deleted_at' => NULL,
                'published' => 1,
            ),
        ));
        
        
    }
}