    <div id="rev_slider_19_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="seo-4" data-source="gallery" style="margin:0px auto;background-color:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
        <!-- START REVOLUTION SLIDER 5.3.0.2.1 fullwidth mode -->
        <div id="rev_slider_19_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.3.0.2.1">
            <ul>
                <!-- SLIDE  -->
                <li data-index="rs-64" data-transition="random-static,random-premium,random" data-slotamount="default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-randomtransition="on" data-easein="default,default,default,default" data-easeout="default,default,default,default" data-masterspeed="310,default,default,default" data-thumb="" data-rotate="0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                    <!-- MAIN IMAGE -->
                    <img src="{{ asset('site/revolution/assets/dummy.png') }}" style='background-color:#000000' alt="" data-lazyload="{{ asset('site/revolution/assets/transparent.png') }}" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
                    <!-- LAYERS -->
                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption   tp-resizeme" id="slide-64-layer-15" data-x="-210" data-y="43" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":310,"speed":1000,"frame":"0","from":"z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5;"><img src="{{ asset('site/revolution/assets/dummy.png') }}" alt="" data-ww="auto" data-hh="auto" data-lazyload="{{ asset('site/revolution/assets/a993b-v2.png') }}" data-no-retina> </div>
                    <!-- LAYER NR. 2 -->
                    <div class="tp-caption   tp-resizeme" id="slide-64-layer-16" data-x="right" data-hoffset="148" data-y="56" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":560,"speed":1000,"frame":"0","from":"z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6;"><img src="{{ asset('site/revolution/assets/dummy.png') }}" alt="" data-ww="230px" data-hh="140px" data-lazyload="{{ asset('site/revolution/assets/a993b-v2.png') }}" data-no-retina> </div>
                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption   tp-resizeme" id="slide-64-layer-17" data-x="178" data-y="574" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":800,"speed":1000,"frame":"0","from":"z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7;"><img src="{{ asset('site/revolution/assets/dummy.png') }}" alt="" data-ww="198px" data-hh="121px" data-lazyload="{{ asset('site/revolution/assets/a993b-v2.png') }}" data-no-retina> </div>
                    <!-- LAYER NR. 4 -->
                    <div class="tp-caption   tp-resizeme" id="slide-64-layer-18" data-x="right" data-hoffset="-103" data-y="bottom" data-voffset="14" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":1180,"speed":1000,"frame":"0","from":"z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8;"><img src="{{ asset('site/revolution/assets/dummy.png') }}" alt="" data-ww="202px" data-hh="123px" data-lazyload="{{ asset('site/revolution/assets/a993b-v2.png') }}" data-no-retina> </div>
                    <!-- LAYER NR. 5 -->
                    <div class="tp-caption   tp-resizeme" id="slide-64-layer-4" data-x="65" data-y="center" data-voffset="-80" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":2620,"split":"words","splitdelay":0.1,"speed":1000,"frame":"0","from":"x:50px;opacity:0;","to":"o:1;","ease":"Power2.easeIn"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9; white-space: nowrap; font-size: 74px; line-height: 82px; font-weight: 900; color: rgba(255, 255, 255, 1.00);font-family: 'Poppins', sans-serif;">Internet Marketing
                        <br>Solutions </div>
                    <!-- LAYER NR. 7 -->
                    <div class="tp-caption rev-btn  tp-resizeme button white" id="slide-64-layer-7" data-x="65" data-y="center" data-voffset="50" data-width="['auto']" data-height="['auto']" data-type="button" data-responsive_offset="on" data-frames='[{"delay":4160,"speed":1000,"frame":"0","from":"x:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","force":true,"to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255, 255, 255, 1.00);bg:rgba(53, 53, 53, 1.00);bs:solid;bw:0 0 0 0;"}]' data-textAlign="['right','right','right','right']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style="z-index: 11; white-space: nowrap; font-size: 14px; line-height: 22px; font-weight: 400; font-family: 'Poppins', sans-serif;text-transform:uppercase;border-color:rgba(0, 0, 0, 1.00);border-radius:30px 30px 30px 30px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Get started now </div>
                    <!-- LAYER NR. 8 -->
                    <div class="tp-caption   tp-resizeme" id="slide-64-layer-19" data-x="right" data-hoffset="" data-y="center" data-voffset="" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":1900,"speed":1000,"frame":"0","from":"x:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 12;"><img src="{{ asset('site/revolution/assets/dummy.png') }}" alt="" data-ww="559px" data-hh="299px" data-lazyload="{{ asset('site/revolution/assets/2b86e-Home-image15.png') }}" data-no-retina> </div>
                </li>
                <!-- SLIDE  -->
                <li data-index="rs-65" data-transition="random-static,random-premium,random" data-slotamount="default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-randomtransition="on" data-easein="default,default,default,default" data-easeout="default,default,default,default" data-masterspeed="300,default,default,default" data-thumb="" data-rotate="0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                    <!-- MAIN IMAGE -->
                    <img src="{{ asset('site/revolution/assets/dummy.png') }}" style='background-color:#000000' alt="" data-lazyload="{{ asset('site/revolution/assets/transparent.png') }}" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
                    <!-- LAYERS -->
                    <!-- LAYER NR. 9 -->
                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-65-layer-13" data-x="center" data-hoffset="" data-y="center" data-voffset="" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":490,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5;"><img src="{{ asset('site/revolution/assets/dummy.png') }}" alt="" data-ww="1808px" data-hh="1042px" data-lazyload="{{ asset('site/revolution/assets/6085e-d1.png') }}" data-no-retina> </div>
                    <!-- LAYER NR. 10 -->
                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-15" id="slide-65-layer-10" data-x="right" data-hoffset="-100" data-y="bottom" data-voffset="-25" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":1420,"speed":1000,"frame":"0","from":"z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6;"><img src="{{ asset('site/revolution/assets/dummy.png') }}" alt="" data-ww="770px" data-hh="524px" data-lazyload="{{ asset('site/revolution/assets/b3d57-102.png') }}" data-no-retina> </div>
                    <!-- LAYER NR. 11 -->
                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-15" id="slide-65-layer-9" data-x="right" data-hoffset="219" data-y="250" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":700,"speed":1000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7;"><img src="{{ asset('site/revolution/assets/dummy.png') }}" alt="" data-ww="133px" data-hh="519px" data-lazyload="{{ asset('site/revolution/assets/b3d57-101.png') }}" data-no-retina> </div>
                    <!-- LAYER NR. 12 -->
                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-65-layer-11" data-x="right" data-hoffset="390" data-y="bottom" data-voffset="-20" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":2140,"speed":1000,"frame":"0","from":"x:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8;"><img src="{{ asset('site/revolution/assets/dummy.png') }}" alt="" data-ww="359px" data-hh="242px" data-lazyload="{{ asset('site/revolution/assets/b3d57-103.png') }}" data-no-retina> </div>
                    <!-- LAYER NR. 13 -->
                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-65-layer-12" data-x="right" data-hoffset="-180" data-y="bottom" data-voffset="" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":2140,"speed":1000,"frame":"0","from":"x:-50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9;"><img src="{{ asset('site/revolution/assets/dummy.png') }}" alt="" data-ww="347px" data-hh="223px" data-lazyload="{{ asset('site/revolution/assets/1cb5d-104.png') }}" data-no-retina> </div>
                    <!-- LAYER NR. 14 -->
                    <div class="tp-caption   tp-resizeme" id="slide-65-layer-4" data-x="65" data-y="center" data-voffset="-80" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":2860,"split":"chars","splitdelay":0.1,"speed":1000,"frame":"0","from":"y:-50px;opacity:0;","to":"o:1;","ease":"Power2.easeIn"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 10; white-space: nowrap; font-size: 74px; line-height: 82px; font-weight: 900; color: rgba(255, 255, 255, 1.00);font-family: 'Poppins', sans-serif;">Internet Marketing
                        <br>Solutions </div>

                    <!-- LAYER NR. 16 -->
                    <div class="tp-caption rev-btn  tp-resizeme button white" id="slide-65-layer-7" data-x="65" data-y="center" data-voffset="50" data-width="['auto']" data-height="['auto']" data-type="button" data-responsive_offset="on" data-frames='[{"delay":4470,"speed":1000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","force":true,"to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255, 255, 255, 1.00);bg:rgba(53, 53, 53, 1.00);bs:solid;bw:0 0 0 0;"}]' data-textAlign="['right','right','right','right']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style="z-index: 12; white-space: nowrap; font-size: 14px; line-height: 22px; font-weight: 400; font-family: 'Poppins', sans-serif;text-transform:uppercase;border-color:rgba(0, 0, 0, 1.00);border-radius:30px 30px 30px 30px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Get started now </div>
                </li>
                <!-- SLIDE  -->
                <li data-index="rs-66" data-transition="random-static,random-premium,random" data-slotamount="default,default,default,default" data-hideafterloop="0" data-hideslideonmobile="off" data-randomtransition="on" data-easein="default,default,default,default" data-easeout="default,default,default,default" data-masterspeed="500,default,default,default" data-thumb="" data-rotate="0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                    <!-- MAIN IMAGE -->
                    <img src="{{ asset('site/revolution/assets/dummy.png') }}" style='background-color:#2f0cc6' alt="" data-lazyload="{{ asset('site/revolution/assets/transparent.png') }}" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
                    <!-- LAYERS -->
                    <!-- LAYER NR. 17 -->
                    <div class="tp-caption   tp-resizeme" id="slide-66-layer-4" data-x="50" data-y="370" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":1930,"speed":1000,"frame":"0","from":"x:50px;opacity:0;","to":"o:1;","ease":"Power3.easeOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; white-space: nowrap; font-size: 74px; line-height: 82px; font-weight: 900; color: rgba(255, 255, 255, 1.00);font-family: 'Poppins', sans-serif;">Internet Marketing
                        <br>Solutions </div>
  
                    <!-- LAYER NR. 19 -->
                    <div class="tp-caption rev-btn  tp-resizeme button white" id="slide-66-layer-7" data-x="50" data-y="center" data-voffset="100" data-width="['auto']" data-height="['auto']" data-type="button" data-responsive_offset="on" data-frames='[{"delay":4000,"speed":1000,"frame":"0","from":"x:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Linear.easeNone","force":true,"to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255, 255, 255, 1.00);bg:rgba(53, 53, 53, 1.00);bs:solid;bw:0 0 0 0;"}]' data-textAlign="['right','right','right','right']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style="z-index: 7; white-space: nowrap; font-size: 14px; line-height: 22px; font-weight: 400; font-family: 'Poppins', sans-serif;text-transform:uppercase;border-color:rgba(0, 0, 0, 1.00);border-radius:30px 30px 30px 30px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Get started now </div>
                    <!-- LAYER NR. 20 -->
                    <div class="tp-caption   tp-resizeme" id="slide-66-layer-28" data-x="right" data-hoffset="-150" data-y="center" data-voffset="28" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":1220,"speed":1000,"frame":"0","from":"z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8;"><img src="{{ asset('site/revolution/assets/dummy.png') }}" alt="" data-ww="641px" data-hh="638px" data-lazyload="{{ asset('site/revolution/assets/d5cac-b1.png') }}" data-no-retina> </div>
                    <!-- LAYER NR. 21 -->
                    <div class="tp-caption   tp-resizeme" id="slide-66-layer-27" data-x="right" data-hoffset="" data-y="center" data-voffset="-100" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":500,"speed":1000,"frame":"0","from":"z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9;"><img src="{{ asset('site/revolution/assets/dummy.png') }}" alt="" data-ww="323px" data-hh="471px" data-lazyload="{{ asset('site/revolution/assets/db2ca-b2.png') }}" data-no-retina> </div>
    
                </li>
            </ul>
            <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>
        </div>
    </div>